[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "crystal-x86_64"
build_on_update = true

[mode.repository.signing]
enabled = true
on_gen = true

[repositories]
repos = [
	"crs:amethyst",
	"crs:jade",
	"crs:jade-gui",
	"crs:malachite",
	"pkg:grub",
]

[repositories.urls]
crs = "https://github.com/crystal-linux/{}"
pkg = "https://github.com/crystal-linux/pkgbuild.{}"
